version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: banco-db
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: banco_user
      POSTGRES_PASSWORD: banco_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: